### ISSUE TITLE
Fails at unarchive of hadoop tar.gz archive

### ISSUE THREAD

**Issue by zakpatterson** [indigo-dc/ansible-role-hadoop#2]
Hi, was trying to use your role here, and ran into this issue, still investigating and reading your code, but it's probably related to this issue:

https://github.com/ansible/ansible-modules-core/issues/3241

Error msg:

```
TASK [hadoop : unarchive] ******************************************************
task path: /home/zak/insilica/hadooproleexample/ansible/roles/hadoop/tasks/install.yml:30

...

fatal: [data0]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"backup": null, "content": null, "copy": false, "creates": "/opt/hadoop-2.7.3", "delimiter": null, "dest": "/opt", "directory_mode": null, "follow": false, "force": null, "group": null, "list_files": false, "mode": null, "original_basename": "hadoop-2.7.3.tar.gz", "owner": null, "regexp": null, "remote_src": null, "selevel": null, "serole": null, "setype": null, "seuser": null, "src": "/opt/hadoop-2.7.3.tar.gz"}}, "msg": "Failed to find handler for \"/opt/hadoop-2.7.3.tar.gz\". Make sure the required command to extract the file is installed.", "stat": {"exists": false}}
```

I made a minimal example project here: https://github.com/zakpatterson/hadoop-vagrant-example

It successfully creates the master node, but then the first slave node fails with the error above.

**Comment by zakpatterson** [comment]
Have the same issue on ansible 2.0.0.2 and 2.2.0.0. 2.2.0.0 reports that `unzip` is unavailable. Testing fixes now.

**Comment by micafer** [comment]
@zakpatterson we have tested it with ansible 2.2.0.0 version and it works.
You can see also Travis tests results:
https://travis-ci.org/indigo-dc/ansible-role-hadoop/jobs/204913176.
If you do not provide more information I will close the issue.
